version: '3'
services:
# namain sendiri
  backend:
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - mysql
    image: 'alterra-agmc-day-7:latest'
    ports:
      - '8080:8080'
#    environment:
# :- default value for reading env
#      APP_PORT: '${APP_PORT:-8080}'
#      DB_USER: '${DB_USER:-admin}'
#      DB_PASS: '${DB_PASS:-admin}'
#      DB_HOST: '${DB_HOST:-mysql}'
#      DB_PORT: '${DB_PORT:-3306}'
#      DB_NAME: '${DB_NAME:-alterra_agmc}'
    networks:
      - infra
  mysql:
    image: 'mysql/mysql-server:5.7'
    restart: always
    ports:
      - '${FORWARD_MYSQL_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME:-alterra_agmc}'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'infra-mysql:/var/lib/mysql'
    networks:
      - infra
networks:
  infra:
    driver: bridge
volumes:
  infra-mysql:
    driver: local